import {
  selectSkills,
  type SkillSelectionRequest,
} from "./selector";
import { composeSkills } from "./composer";
import {
  generateSkill,
  type StructuredSkillGenerator,
} from "./factory";
import { createSkill, listSkills } from "./repository";

export class SkillService {
  constructor(
    private readonly generator: StructuredSkillGenerator,
  ) {}

  async resolve(
    request: SkillSelectionRequest & {
      userId: string;
      constraints?: string[];
      expectedOutput?: string;
    },
  ) {
    const selected = await selectSkills(request);

    if (selected.length > 0) {
      return {
        created: false,
        selected: selected.map((item) => ({
          skill: item.skill,
          score: item.score,
          reason: item.reason,
        })),
        package: composeSkills(
          selected.map((item) => item.skill),
        ),
      };
    }

    const generated = await generateSkill(
      this.generator,
      {
        objective: request.objective,
        taskType: request.taskType,
        requiredCapabilities: request.requiredCapabilities ?? [],
        requiredTools: request.requiredTools ?? [],
        constraints: request.constraints ?? [],
        expectedOutput: request.expectedOutput,
      },
      request.userId,
    );

    const saved = await createSkill(generated);

    return {
      created: true,
      selected: [
        {
          skill: saved,
          score: 1,
          reason: "Skill generated by Skill Factory.",
        },
      ],
      package: composeSkills([saved]),
    };
  }
}

export async function getAvailableSkills(userId: string) {
  if (!userId) {
    throw new Error("userId is required.");
  }

  const skills = await listSkills({ status: "active" });

  return skills.filter(
    (skill) =>
      skill.visibility === "system" ||
      skill.visibility === "marketplace" ||
      skill.authorId === userId,
  );
}
