"use client";
import { useEffect, useRef, useState } from "react";
import { onAuthStateChanged, type User } from "firebase/auth";
import { auth } from "@/lib/firebase/client";

export default function StoragePage() {
  const [user, setUser] = useState<User | null>(null); const [files, setFiles] = useState<Array<{ path: string; filename: string; sizeBytes: number }>>([]); const [requests, setRequests] = useState<Array<{ id: string; reason: string; facingMode: string }>>([]); const [busy, setBusy] = useState(false); const videoRef = useRef<HTMLVideoElement>(null);
  const token = async () => user ? user.getIdToken() : "";
  const refresh = async (current = user) => { if (!current) return; const t = await current.getIdToken(); const h = { Authorization: `Bearer ${t}` }; const [f, r] = await Promise.all([fetch("/api/storage/permanent", { headers: h, cache: "no-store" }), fetch("/api/camera/requests", { headers: h, cache: "no-store" })]); if (f.ok) setFiles((await f.json()).files ?? []); if (r.ok) setRequests((await r.json()).requests ?? []); };
  useEffect(() => onAuthStateChanged(auth, current => { setUser(current); if (current) refresh(current); }), []);
  const upload = async (file: File) => { if (!user) return; setBusy(true); try { const t = await token(); const form = new FormData(); form.append("file", file); const response = await fetch("/api/storage/permanent", { method: "POST", headers: { Authorization: `Bearer ${t}` }, body: form }); if (!response.ok) throw new Error((await response.json()).error); await refresh(); } finally { setBusy(false); } };
  const capture = async (requestId: string, facingMode: "user" | "environment") => { if (!user || !videoRef.current) return; setBusy(true); try { const stream = await navigator.mediaDevices.getUserMedia({ video: { facingMode } }); videoRef.current.srcObject = stream; await videoRef.current.play(); await new Promise(r => setTimeout(r, 800)); const canvas = document.createElement("canvas"); canvas.width = videoRef.current.videoWidth; canvas.height = videoRef.current.videoHeight; canvas.getContext("2d")?.drawImage(videoRef.current, 0, 0); stream.getTracks().forEach(t => t.stop()); const blob = await new Promise<Blob>((resolve, reject) => canvas.toBlob(b => b ? resolve(b) : reject(new Error("Camera capture failed")), "image/jpeg", .92)); const t = await token(); const response = await fetch(`/api/camera/complete`, { method: "POST", headers: { Authorization: `Bearer ${t}`, "content-type": "image/jpeg", "x-camera-request-id": requestId }, body: blob }); if (!response.ok) throw new Error((await response.json()).error); await refresh(); } finally { setBusy(false); } };
  return <main className="min-h-screen bg-[#070a12] text-white p-6"><div className="mx-auto max-w-6xl"><h1 className="text-3xl font-bold">Stockage permanent</h1><p className="mt-2 text-white/55">Vos fichiers restent associés à votre compte. Les agents peuvent les lire et les manipuler uniquement selon leurs permissions.</p><div className="mt-6 rounded-3xl border border-white/10 bg-[#0d1220] p-6"><label className="inline-flex cursor-pointer rounded-xl bg-violet-600 px-5 py-3 font-semibold"><input type="file" className="hidden" disabled={busy} onChange={e => e.target.files?.[0] && upload(e.target.files[0])}/>Importer un fichier</label><div className="mt-6 space-y-2">{files.map(file => <div key={file.path} className="flex items-center justify-between rounded-xl border border-white/10 p-4"><span>{file.filename}</span><span className="text-xs text-white/45">{(file.sizeBytes / 1024).toFixed(1)} KB</span></div>)}{!files.length && <p className="text-sm text-white/40">Aucun fichier permanent.</p>}</div></div><div className="mt-6 rounded-3xl border border-white/10 bg-[#0d1220] p-6"><h2 className="text-xl font-semibold">Demandes caméra des agents</h2><p className="mt-2 text-sm text-white/50">La caméra n'est jamais activée silencieusement. Une demande d'agent doit être acceptée par l'utilisateur et expire automatiquement.</p><video ref={videoRef} className="mt-4 hidden w-full max-w-xl rounded-xl" playsInline muted /> <div className="mt-5 space-y-3">{requests.map(r => <div key={r.id} className="rounded-xl border border-amber-400/20 bg-amber-400/5 p-4"><p className="text-sm">{r.reason}</p><button disabled={busy} onClick={() => capture(r.id, r.facingMode === "user" ? "user" : "environment")} className="mt-3 rounded-lg bg-emerald-600 px-4 py-2 text-sm font-semibold">Autoriser et prendre la photo</button></div>)}{!requests.length && <p className="text-sm text-white/40">Aucune demande en attente.</p>}</div></div></div></main>;
}
